# Generated by Django 5.2.8 on 2026-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_paymentwebhooklog_one_per_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentwebhooklog",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="transactionhistory",
            options={
                "ordering": ["-updated_at"],
                "verbose_name_plural": "Transaction histories",
            },
        ),
        migrations.RenameIndex(
            model_name="paymentwebhooklog",
            new_name="payments_pa_source_00da56_idx",
            old_name="payments_pa_source_6e0b0d_idx",
        ),
        migrations.AlterField(
            model_name="paymentwebhooklog",
            name="source",
            field=models.CharField(
                choices=[
                    ("pesapal_ipn", "Pesapal IPN"),
                    ("pesapal_status_sync", "Pesapal status sync (poll)"),
                    ("azampay_legacy", "AzamPay legacy"),
                ],
                default="pesapal_ipn",
                max_length=40,
            ),
        ),
    ]
