# Generated by Django 5.2.8 on 2026-04-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "sermon_type",
                    models.CharField(
                        choices=[("video", "Video"), ("audio", "Audio")],
                        default="video",
                        max_length=10,
                    ),
                ),
                (
                    "media_url",
                    models.URLField(help_text="URL to the video or audio file"),
                ),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("date", models.DateField()),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
