# Generated by Django 5.2.8 on 2026-04-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_timetable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="books/covers/"),
                ),
                ("file", models.FileField(upload_to="books/files/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("html", "HTML")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
