# Generated by Django 5.2.8 on 2026-04-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_representative_order_representative"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sermon",
            old_name="thumbnail_url",
            new_name="youtube_url",
        ),
        migrations.RemoveField(
            model_name="sermon",
            name="media_url",
        ),
        migrations.AddField(
            model_name="sermon",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="sermons/audio/"),
        ),
        migrations.AddField(
            model_name="sermon",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sermon",
            name="duration",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sermon",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sermon",
            name="speaker",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sermon",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="sermons/thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="sermon",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sermon",
            name="sermon_type",
            field=models.CharField(
                choices=[("video", "Video"), ("audio", "Audio")], max_length=10
            ),
        ),
    ]
