# Generated by Django 5.2.8 on 2026-04-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_order_external_reference_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="external_reference",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="webhook_received",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="external_reference",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
