# Generated by Django 5.2.8 on 2026-04-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_order_paid_at_payment_external_reference_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="raw_response",
            new_name="raw_provider_response",
        ),
        migrations.AddField(
            model_name="payment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
