# Generated by Django 5.2.8 on 2026-04-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_rename_raw_response_payment_raw_provider_response_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="raw_provider_response",
            new_name="raw_response",
        ),
        migrations.RemoveField(
            model_name="order",
            name="paid_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="external_reference",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="last_checked_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="provider_reference",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="retry_count",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="verified",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="verified_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="webhook_received",
        ),
        migrations.AlterField(
            model_name="order",
            name="external_reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
