# Generated by Django 5.2.8 on 2026-05-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_rename_raw_provider_response_payment_raw_response_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="external_reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_transaction_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
