# Generated by Django 6.0.4 on 2026-05-01 21:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_remove_payment_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="audio_file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
