# Generated by Django 6.0.4 on 2026-05-01 22:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_alter_sermon_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="audio_file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="audio"
            ),
        ),
        migrations.AlterField(
            model_name="sermon",
            name="thumbnail_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
