# Generated by Django 6.0.4 on 2026-05-07 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_alter_sermon_audio_file_alter_sermon_thumbnail_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Partnership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(choices=[("USD", "USD"), ("TSH", "TSH")], max_length=3)),
                ("gift_type", models.CharField(choices=[("ONE_TIME", "One Time"), ("RECURRING", "Recurring")], default="ONE_TIME", max_length=12)),
                ("frequency", models.CharField(blank=True, choices=[("WEEKLY", "Every week"), ("EVERY_2_WEEKS", "Every 2 weeks"), ("MONTHLY", "Every month"), ("FIRST_AND_FIFTEENTH", "1st & 15th monthly")], max_length=30, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("fund", models.CharField(blank=True, default="Where Needed Most", max_length=120)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("district", models.CharField(blank=True, max_length=120)),
                ("ward", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("partner_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="partnerships", to="account.partnertype")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="partnerships", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
