# Generated by Django 5.2.8 on 2026-05-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_sermon_is_kickoff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="is_kickoff",
            field=models.BooleanField(
                default=False,
                help_text="Kick-Off tab (audio only): visible for 5 days from upload (created_at).",
            ),
        ),
    ]
