# Generated by Django 5.2.8 on 2026-05-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0025_events_unified_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventtestimony",
            options={
                "ordering": ["order", "id"],
                "verbose_name_plural": "Event testimonies",
            },
        ),
    ]
