# Generated by Django 5.2.8 on 2026-05-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0028_payment_external_reference_norm_and_completed_at_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
