# Generated by Django 5.2.8 on 2026-05-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0037_partnership_guest_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnership",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
