# Generated by Django 5.2.8 on 2026-05-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0038_alter_partnership_guest_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-created_at", "-start_date"]},
        ),
    ]
