# Generated by Django 5.2.8 on 2026-05-24 10:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0042_emailotpchallenge_admin_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devotional",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
