"""
Django settings for mpanzi project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# from decouple import config
from pathlib import Path

import os

from dotenv import load_dotenv  
load_dotenv()  # Load environment variables from .env file if it exists
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# # Load project-level environment overrides from loadenv.env if present
from pathlib import Path as _Path
# _loadenv_path = BASE_DIR / 'loadenv.env'
# if _loadenv_path.exists():
#     # call load_dotenv with the explicit path so variables in loadenv.env are loaded
#     load_dotenv(str(_loadenv_path))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = "django-insecure-kav^xz_pq#^pqyx^%g(t+ei2nrpkler)jggy60eq%u(me(7*dq"
SECRET_KEY = os.getenv("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = 
DEBUG = os.getenv("DEBUG", "False") == "True"
# ALLOWED_HOSTS = ["0.0.0.0", "127.0.0.1","causal-gratify-carat.ngrok-free.dev", "192.168.1.189","*", "localhost"]

ALLOWED_HOSTS = ['mpnazi-production.up.railway.app', '127.0.0.1', 'localhost']
# CSRF_TRUSTED_ORIGINS = [
#     "https://causal-gratify-carat.ngrok-free.dev",
# ]
CSRF_TRUSTED_ORIGINS = ["https://mpnazi-production.up.railway.app", "http://127.0.0.1:8000", "http://localhost:8000"]

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "account",
    "payments",
    "cart_payment",
    "django_q",
    "notifications",
    "prayers",
    "app_version",
    "channels",

    "django_summernote",
    'cloudinary',
    'cloudinary_storage',
]

# django-summernote (WYSIWYG for Devotional bodies in admin)
X_FRAME_OPTIONS = "SAMEORIGIN"
SUMMERNOTE_CONFIG = {
    "iframe": True,
    "summernote": {
        "width": "100%",
        "height": "480",
        "toolbar": [
            ["style", ["style"]],
            ["font", ["bold", "italic", "underline", "clear"]],
            ["fontsize", ["fontsize"]],
            ["para", ["ul", "ol", "paragraph"]],
            ["insert", ["link"]],
            ["view", ["fullscreen", "codeview"]],
        ],
    },
    "css_for_widget": (),
    "js_for_widget": (),
}

# Django REST Framework defaults
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # Public content by default; lock down sensitive endpoints explicitly (e.g. orders, profile).
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Use optional JWT so stale Bearer tokens on public GETs do not force 401
        'account.authentication.OptionalJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mpanzi.urls"

# Registration OTP + rate limits. Set REDIS_URL in production (e.g. redis://127.0.0.1:6379/1).
REDIS_URL = os.environ.get("REDIS_URL", "").strip()
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "mpanzi-default-cache",
        }
    }

REGISTER_OTP_CACHE_TTL = 600  # 10 minutes — pending registration in cache

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },

]


import cloudinary

cloudinary.config(
    cloud_name=os.environ.get('CLOUD_NAME'),
    api_key=os.environ.get('API_KEY'),
    api_secret=os.environ.get('API_SECRET'),
    secure=True
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUD_NAME'),
    'API_KEY': os.environ.get('API_KEY'),
    'API_SECRET': os.environ.get('API_SECRET'),
    'MAGIC_FILE_PATH': 'magic',
}
WSGI_APPLICATION = "mpanzi.wsgi.application"
ASGI_APPLICATION = "mpanzi.asgi.application"

ADMIN_DASHBOARD_URL = os.environ.get(
    "ADMIN_DASHBOARD_URL", "https://mpnazi-production.up.railway.app"
)

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
    }
DB_LIVE = os.getenv("DB_LIVE")

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DB_LIVE in ["False", False]:
    DATABASES = {
        "default": {
            "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.postgresql"),
            "NAME": os.environ.get("DB_NAME", "mpanzi"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "Inno-997"),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE":  "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
        }
    }

#postgresql://postgres:ovnTJVmaAJrBsosNpIrYZhZOKEiUOTbf@switchyard.proxy.rlwy.net:27501/railway

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# 1. Static Configuration
STATIC_URL = '/static/'

# Directories where Django will look for YOUR custom static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# 🌟 2. CRITICAL FIX: The destination folder for collectstatic 🌟
# This is where all files (including Summernote's) will be gathered.
STATIC_ROOT = BASE_DIR / 'staticfiles' 


STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# 3. Media Configuration (Needed for Summernote uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS").lower() in ("1", "true", "yes")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
# Gmail app passwords are often pasted with spaces — strip them.
EMAIL_HOST_PASSWORD = (os.environ.get("EMAIL_HOST_PASSWORD") or "").replace(" ", "")
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "Mpanzi Ministries <innocentphilbert39@gmail.com>",
)

# ── Pesapal API 3.0 ────────────────────────────────────────────────────────
# sandbox: cybqa + demo keys | live: pay.pesapal.com + keys from Pesapal email
# Docs: https://developer.pesapal.com/how-to-integrate/e-commerce/api-30-json/api-reference
DEFAULT_PAYMENT_PROVIDER = os.environ.get("DEFAULT_PAYMENT_PROVIDER", "PESAPAL")
PESAPAL_ENV = os.environ.get("PESAPAL_ENV", "sandbox")
PESAPAL_BASE_URL = os.environ.get(
    "PESAPAL_BASE_URL",
    "https://cybqa.pesapal.com/pesapalv3"
    if PESAPAL_ENV == "sandbox"
    else "https://pay.pesapal.com/v3",
).rstrip("/")
# Strip whitespace; use quotes in .env when values contain + / = (see .env.example)
PESAPAL_CONSUMER_KEY = os.environ.get("PESAPAL_CONSUMER_KEY", "").strip()
PESAPAL_CONSUMER_SECRET = os.environ.get("PESAPAL_CONSUMER_SECRET", "").strip()
# Public URL Pesapal redirects the customer to after payment (Flutter deep link or web page)
PESAPAL_CALLBACK_URL = os.environ.get(
    "PESAPAL_CALLBACK_URL",
    "https://causal-gratify-carat.ngrok-free.dev/api/payments/callback/",
).strip()
PESAPAL_CANCELLATION_URL = os.environ.get("PESAPAL_CANCELLATION_URL", "").strip()
# IPN URL — must be publicly reachable; register in Pesapal dashboard or auto-register
PESAPAL_IPN_URL = os.environ.get(
    "PESAPAL_IPN_URL",
    "https://causal-gratify-carat.ngrok-free.dev/api/payments/ipn/",
).strip()
# Optional: pre-registered notification_id from Pesapal IPN registration
PESAPAL_NOTIFICATION_ID = os.environ.get("PESAPAL_NOTIFICATION_ID", "").strip()

# Ruhusu trailing slash automatically
APPEND_SLASH = True

# ── FCM HTTP v1 (Google service account JSON string in env; never commit) ──
FCM_PROJECT_ID = os.environ.get("FCM_PROJECT_ID", "").strip()
GOOGLE_SERVICE_ACCOUNT_JSON = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON", "").strip()

# Django-Q2: run `python manage.py qcluster` alongside gunicorn to process push tasks.
Q_CLUSTER = {
    "name": "mpanzi",
    "workers": 2,
    "timeout": 120,
    "retry": 180,
    "queue_limit": 64,
    "orm": "default",
    "bulk": 10,
}






# print("EMAIL_HOST_USER:", EMAIL_HOST_USER)
# print("EMAIL_HOST_PASSWORD:", EMAIL_HOST_PASSWORD)
# print("PESAPAL_BASE_URL:", PESAPAL_BASE_URL)
# print("PESAPAL_CONSUMER_KEY:", PESAPAL_CONSUMER_KEY)
# print("PESAPAL_CONSUMER_SECRET:", PESAPAL_CONSUMER_SECRET)
# print("PESAPAL_IPN_URL:", PESAPAL_IPN_URL)
# print("PESAPAL_CALLBACK_URL:", PESAPAL_CALLBACK_URL)
# print("PESAPAL_CANCELLATION_URL:", PESAPAL_CANCELLATION_URL)
# print("PESAPAL_NOTIFICATION_ID:", PESAPAL_NOTIFICATION_ID)
# print("DEFAULT_PAYMENT_PROVIDER:", DEFAULT_PAYMENT_PROVIDER)