"""
Django settings for mpanzi project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# from decouple import config
from pathlib import Path

import os

from dotenv import load_dotenv  
load_dotenv()  # Load environment variables from .env file if it exists
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# # Load project-level environment overrides from loadenv.env if present
from pathlib import Path as _Path
# _loadenv_path = BASE_DIR / 'loadenv.env'
# if _loadenv_path.exists():
#     # call load_dotenv with the explicit path so variables in loadenv.env are loaded
#     load_dotenv(str(_loadenv_path))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-kav^xz_pq#^pqyx^%g(t+ei2nrpkler)jggy60eq%u(me(7*dq"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ["0.0.0.0", "127.0.0.1","causal-gratify-carat.ngrok-free.dev", "192.168.1.189","*", "localhost"]

ALLOWED_HOSTS = ['mpnazi-production.up.railway.app', '127.0.0.1', 'localhost','*']

CSRF_TRUSTED_ORIGINS = ["https://mpnazi-production.up.railway.app", "http://127.0.0.1:8000"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "account",


    'cloudinary',
    'cloudinary_storage',
]

# Django REST Framework defaults
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mpanzi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },

]


import cloudinary

cloudinary.config(
    cloud_name=os.environ.get('CLOUD_NAME'),
    api_key=os.environ.get('API_KEY'),
    api_secret=os.environ.get('API_SECRET'),
    secure=True
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUD_NAME'),
    'API_KEY': os.environ.get('API_KEY'),
    'API_SECRET': os.environ.get('API_SECRET'),
    'MAGIC_FILE_PATH': 'magic',
}
WSGI_APPLICATION = "mpanzi.wsgi.application"
DB_LIVE = os.getenv("DB_LIVE")

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DB_LIVE in ["False", False]:
    DATABASES = {
        "default": {
            "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.postgresql"),
            "NAME": os.environ.get("DB_NAME", "mpanzi"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "Inno-997"),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE":  "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
        }
    }

#postgresql://postgres:ovnTJVmaAJrBsosNpIrYZhZOKEiUOTbf@switchyard.proxy.rlwy.net:27501/railway

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# 1. Static Configuration
STATIC_URL = '/static/'

# Directories where Django will look for YOUR custom static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# 🌟 2. CRITICAL FIX: The destination folder for collectstatic 🌟
# This is where all files (including Summernote's) will be gathered.
STATIC_ROOT = BASE_DIR / 'staticfiles' 


STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# 3. Media Configuration (Needed for Summernote uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# AzamPay configuration - loaded from environment. Do NOT commit secrets.
# AZAMPAY_APP_NAME = os.environ.get('AZAMPAY_APP_NAME')
# AZAMPAY_CLIENT_ID = os.environ.get('AZAMPAY_CLIENT_ID')
# AZAMPAY_CLIENT_SECRET = os.environ.get('AZAMPAY_CLIENT_SECRET')
# AZAMPAY_BASE_URL = os.environ.get('AZAMPAY_BASE_URL')
# AZAMPAY_CALLBACK_URL = os.environ.get('AZAMPAY_CALLBACK_URL')

# Basic validation during startup (helpful in development)
AZAMPAY_AUTH_BASE_URL= "https://authenticator-sandbox.azampay.co.tz"
AZAMPAY_API_BASE_URL="https://sandbox.azampay.co.tz"
AZAMPAY_CLIENT_ID="474cba96-1296-4b5d-80db-e09c56f57762"
AZAMPAY_CLIENT_SECRET="U93YbqvOy5q4yevipbl7CaAOy91WVlS0XC+T1CC8sPK5UAAOmWQdKld6Qd2MgYnYC4G4viczKToWvHBX07LoJhXBph9nY6Ufyp6twwpOzOAIXsnvkJntpSOwCx6I2Aw1AmDAfMr2/Qrt3C6KoGMKfX0keN6Z+BVVjHTlyqMrkHlJehlqQ8IAPGQ0aK5FK8jYr2bkHU16pzSR8x19HbOKxLLJTaQpNpQMIOmwwwUDkn5LPEa//liAydf9ZAhFlhfq92uZcvd7qYVSdKrKop9XXGIuQfqWz6f/jr8Srm5r6vntTnGo6GBlrMiRHlywCS8TgA91R48I0h/kL+8U1kh7iSJYvos5fl1bFnTFps3fbNHGjzC/It/gINxMeshja07WXnbBiZgeXGoSiU/OLv/JJPsbkmV2S91ynIzjNnOaMZiybhVGcMWMi3+KtnU/Vxh7e8YNxC87pmsGL7lHTzy7iDV135Jqgh8/782N4MSkgCCRWeoswHKzjcEeCsifbVmzieq9KcNX6tLhUPnrgv0X7/RJXgJkBQ/34PqUewnUIAymXWix6dFz/gGsnqxvUXQJIDlg1gZ/IuHFLyGxUhgFx4yhQoGEM3YhjUQZEaXo2U7iE9uj9qr2sSVtELYt8UhgSv2cxLLkuaIvA71OLwxK04iaU/h4m0H0p+srBdk1kKI="
# AZAMPAY_CALLBACK_URL="https://abc123.ngrok.io/api/payments/azampay/callback/""
AZAMPAY_CALLBACK_URL="https://causal-gratify-carat.ngrok-free.dev/api/payments/webhook/"
AZAMPAY_APP_NAME="housekeeper"
# Ruhusu trailing slash automatically
APPEND_SLASH = True
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# AZAMPAY_BASE_URL = config('AZAMPAY_BASE_URL', default='')
# AZAMPAY_APP_NAME = config('AZAMPAY_APP_NAME', default='')
# AZAMPAY_CLIENT_ID = config('AZAMPAY_CLIENT_ID', default='')
# AZAMPAY_CLIENT_SECRET = config('AZAMPAY_CLIENT_SECRET', default='')
# AZAMPAY_CALLBACK_URL = config('AZAMPAY_CALLBACK_URL', default='')


# print("AZAMPAY_AUTH_BASE_URL:", AZAMPAY_AUTH_BASE_URL)
# print("AZAMPAY_API_BASE_URL:", AZAMPAY_API_BASE_URL)
