# Generated by Django 5.2.8 on 2026-05-14 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart_payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cartorderpayment",
            new_name="cart_paymen_order_i_e33ea4_idx",
            old_name="cart_pay_order_status_idx",
        ),
    ]
