# Generated by Django 5.2.8 on 2026-05-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prayers", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="prayerrequest",
            new_name="prayers_pra_status_205703_idx",
            old_name="prayers_pra_status_8a0f0d_idx",
        ),
        migrations.RenameIndex(
            model_name="prayerrequest",
            new_name="prayers_pra_categor_f354c9_idx",
            old_name="prayers_pra_categor_6e8b2a_idx",
        ),
    ]
